# Generated by Django 4.1.5 on 2023-02-03 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookTable',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=20)),
                ('isbn', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MemberTable',
            fields=[
                ('member_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='BorrowTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('return_date', models.DateTimeField()),
                ('book_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='library_catalogue.booktable')),
                ('member_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='library_catalogue.membertable')),
            ],
        ),
    ]
